---
# Source: nfs-subdir-external-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.11
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: RELEASE-NAME
  name: RELEASE-NAME-nfs-subdir-external-provisioner
---
# Source: nfs-subdir-external-provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.11
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: RELEASE-NAME
  name: volumen-nfs
  annotations:
provisioner: cluster.local/RELEASE-NAME-nfs-subdir-external-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "true"
---
# Source: nfs-subdir-external-provisioner/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.11
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: RELEASE-NAME
  name: RELEASE-NAME-nfs-subdir-external-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
# Source: nfs-subdir-external-provisioner/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.11
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: RELEASE-NAME
  name: run-RELEASE-NAME-nfs-subdir-external-provisioner
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-nfs-subdir-external-provisioner
    namespace: nfs-provisioner
roleRef:
  kind: ClusterRole
  name: RELEASE-NAME-nfs-subdir-external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
# Source: nfs-subdir-external-provisioner/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.11
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: RELEASE-NAME
  name: leader-locking-RELEASE-NAME-nfs-subdir-external-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
# Source: nfs-subdir-external-provisioner/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.11
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: RELEASE-NAME
  name: leader-locking-RELEASE-NAME-nfs-subdir-external-provisioner
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-nfs-subdir-external-provisioner
    namespace: nfs-provisioner
roleRef:
  kind: Role
  name: leader-locking-RELEASE-NAME-nfs-subdir-external-provisioner
  apiGroup: rbac.authorization.k8s.io
---
# Source: nfs-subdir-external-provisioner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-nfs-subdir-external-provisioner
  labels:
    chart: nfs-subdir-external-provisioner-4.0.11
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: RELEASE-NAME
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
      release: RELEASE-NAME
  template:
    metadata:
      annotations:
      labels:
        app: nfs-subdir-external-provisioner
        release: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-nfs-subdir-external-provisioner
      containers:
        - name: nfs-subdir-external-provisioner
          image: "k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-subdir-external-provisioner-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/RELEASE-NAME-nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: 172.31.11.196
            - name: NFS_PATH
              value: /data/nfs
      volumes:
        - name: nfs-subdir-external-provisioner-root
          nfs:
            server: 172.31.11.196
            path: /data/nfs
