kind:           Service
apiVersion:     v1            

metadata:
    name:       mi-servicio

spec:
    type: ClusterIP
    ports:
        - port: 8080
          targetPort: 80
    selector:                   # Creadas desde la plantilla
        app: temis-web      # app: temis-web
