kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1

metadata:
  name: kibana-hpa

spec:

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kibana

  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
